import { chmod, mkdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";

export interface InitGitHooksResult {
  rootPath: string;
  hookPaths: string[];
  preExisting: string[];
}

const isWindows = process.platform === "win32";

const preCommitHook = isWindows
  ? [
      "@echo off",
      "REM Generated by codex-plugin-doctor init git-hooks",
      "REM Validates the plugin package before every commit.",
      "",
      "echo Codex Plugin Doctor: running pre-commit validation...",
      "",
      "call npx --yes codex-plugin-doctor check . --profile ci",
      "",
      "if %ERRORLEVEL% neq 0 (",
      "  echo.",
      "  echo Plugin validation failed. Commit blocked.",
      "  echo Run 'codex-plugin-doctor check .' to see full diagnostics.",
      "  exit /b 1",
      ")",
      ""
    ].join("\r\n")
  : [
      "#!/usr/bin/env sh",
      "# Generated by codex-plugin-doctor init git-hooks",
      "# Validates the plugin package before every commit.",
      "",
      "echo \"Codex Plugin Doctor: running pre-commit validation...\"",
      "",
      "npx --yes codex-plugin-doctor check . --profile ci",
      "",
      "if [ $? -ne 0 ]; then",
      "  echo \"\"",
      "  echo \"Plugin validation failed. Commit blocked.\"",
      "  echo \"Run 'codex-plugin-doctor check .' to see full diagnostics.\"",
      "  exit 1",
      "fi",
      ""
    ].join("\n");

const prePushHook = isWindows
  ? [
      "@echo off",
      "REM Generated by codex-plugin-doctor init git-hooks",
      "REM Validates the plugin package before every push.",
      "",
      "echo Codex Plugin Doctor: running pre-push validation...",
      "",
      "call npx --yes codex-plugin-doctor check . --profile ci --runtime",
      "",
      "if %ERRORLEVEL% neq 0 (",
      "  echo.",
      "  echo Plugin validation failed. Push blocked.",
      "  echo Run 'codex-plugin-doctor check . --runtime' to see full diagnostics.",
      "  exit /b 1",
      ")",
      ""
    ].join("\r\n")
  : [
      "#!/usr/bin/env sh",
      "# Generated by codex-plugin-doctor init git-hooks",
      "# Validates the plugin package before every push.",
      "",
      "echo \"Codex Plugin Doctor: running pre-push validation...\"",
      "",
      "npx --yes codex-plugin-doctor check . --profile ci --runtime",
      "",
      "if [ $? -ne 0 ]; then",
      "  echo \"\"",
      "  echo \"Plugin validation failed. Push blocked.\"",
      "  echo \"Run 'codex-plugin-doctor check . --runtime' to see full diagnostics.\"",
      "  exit 1",
      "fi",
      ""
    ].join("\n");

const hookExtension = isWindows ? ".bat" : "";

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await stat(filePath);
    return true;
  } catch {
    return false;
  }
}

async function writeHook(hookPath: string, content: string, force: boolean): Promise<boolean> {
  const exists = await fileExists(hookPath);

  if (exists && !force) {
    return false;
  }

  await writeFile(hookPath, content, "utf8");

  if (process.platform !== "win32") {
    await chmod(hookPath, 0o755);
  }

  return exists;
}

export interface RemoveGitHooksResult {
  rootPath: string;
  removed: string[];
  skipped: string[];
}

export async function removeGitHooks(targetPath: string): Promise<RemoveGitHooksResult> {
  const rootPath = path.resolve(targetPath);
  const hooksDir = path.join(rootPath, ".git", "hooks");
  const hookNames = [`pre-commit${hookExtension}`, `pre-push${hookExtension}`, "pre-commit", "pre-push"];
  const removed: string[] = [];
  const skipped: string[] = [];

  for (const name of hookNames) {
    const hookPath = path.join(hooksDir, name);

    if (await fileExists(hookPath)) {
      const content = await import("node:fs/promises").then((m) => m.readFile(hookPath, "utf8"));

      if (content.includes("Generated by codex-plugin-doctor init git-hooks")) {
        await import("node:fs/promises").then((m) => m.rm(hookPath));
        removed.push(hookPath);
      } else {
        skipped.push(hookPath);
      }
    }
  }

  return { rootPath, removed, skipped };
}

export async function initGitHooks(
  targetPath: string,
  options: { force?: boolean } = {}
): Promise<InitGitHooksResult> {
  const rootPath = path.resolve(targetPath);
  const hooksDir = path.join(rootPath, ".git", "hooks");
  const force = options.force ?? false;

  await mkdir(hooksDir, { recursive: true });

  const hookPaths: string[] = [];
  const preExisting: string[] = [];

  const preCommitPath = path.join(hooksDir, `pre-commit${hookExtension}`);
  const prePushPath = path.join(hooksDir, `pre-push${hookExtension}`);

  const wasPreCommitExisting = await writeHook(preCommitPath, preCommitHook, force);
  hookPaths.push(preCommitPath);

  if (wasPreCommitExisting) {
    preExisting.push(preCommitPath);
  }

  const wasPrePushExisting = await writeHook(prePushPath, prePushHook, force);
  hookPaths.push(prePushPath);

  if (wasPrePushExisting) {
    preExisting.push(prePushPath);
  }

  return { rootPath, hookPaths, preExisting };
}
